Typeless changes for PHP, MySQL and PhpMyAdmin and changes related to gear script removal in abstract.
Util wip.

PHP/Abstract changes.

Fix to restart hook.

Take out php ctl script.

Mysql typeless (still need to fix for standalone case and moves)

fix misc vars in php/mysql

phpmyadmin typeless.

Re-enable ns log dirs.

Conflicts:
	stickshift/abstract/abstract/info/lib/util

diff --git a/cartridges/phpmyadmin-3.4/info/hooks/configure b/cartridges/phpmyadmin-3.4/info/hooks/configure
--- a/cartridges/phpmyadmin-3.4/info/hooks/configure
+++ b/cartridges/phpmyadmin-3.4/info/hooks/configure
@@ -32,7 +32,6 @@ setup_embedded_configure "$1" $2 $3
 disable_cgroups
 
 PHPMYADMIN_DIR=$(get_cartridge_instance_dir "$cartridge_type")
-PHPMYADMIN_CTL_SCRIPT="$PHPMYADMIN_DIR/${application}_phpmyadmin_ctl.sh"
 
 if [ ! -f "$APP_HOME/.env/OPENSHIFT_MYSQL_DB_USERNAME" ] ||
    [ ! -f "$APP_HOME/.env/OPENSHIFT_MYSQL_DB_PASSWORD" ] ||
@@ -80,11 +79,6 @@ IP=`embedded_find_open_ip $uid $APP_HOME`
 $CART_INFO_DIR/bin/deploy_httpd_config.sh $application $uuid $IP
 
 #
-# Create simple phpmyadmin start / stop script
-#
-ln -s $CART_INFO_DIR/bin/phpmyadmin_ctl.sh $PHPMYADMIN_CTL_SCRIPT
-
-#
 # Add config to show disabled pages instead of default apache Forbidden page
 #
 ln -s $CART_INFO_DIR/configuration/disabled_pages.conf $PHPMYADMIN_DIR/conf.d/disabled_pages.conf
@@ -99,17 +93,13 @@ chown root.root -R "$PHPMYADMIN_DIR/conf" "$PHPMYADMIN_DIR/conf.d"
 chown root.root "$PHPMYADMIN_DIR"
 observe_setup_var_lib_dir "$PHPMYADMIN_DIR"
 
-#
-# Create environment variables. This MUST be before starting phpmyadmin as the CTL script relies on these.
-#
 create_standard_cart_env_vars
 echo "export OPENSHIFT_PHPMYADMIN_IP='$IP'" > $APP_HOME/.env/OPENSHIFT_PHPMYADMIN_IP
-
 
 #
 # Start the server
 #
-run_as_user "$PHPMYADMIN_CTL_SCRIPT start" || error "Failed to start ${application}" 121
+run_as_user "${CART_INFO_DIR}/bin/app_ctl.sh start" || error "Failed to start ${application}" 121
 
 
 #
diff --git a/stickshift/abstract/abstract/info/lib/util b/stickshift/abstract/abstract/info/lib/util
--- a/stickshift/abstract/abstract/info/lib/util
+++ b/stickshift/abstract/abstract/info/lib/util
@@ -10,6 +10,29 @@ function source_if_exists {
 }
 
 
+function get_gear_start_order {
+    local start_order=`ls $APP_HOME/{} 2>/dev/null`
+    echo $start_order
+}
+
+#
+# Function to get the start/stop order on the basis of installed carts
+# TODO: Replace with reading from start/stop order files when implemented
+#
+function get_component_order {
+    (cd $APP_HOME; ls -d {mongodb-2.0,mysql-5.1,postgresql-8.4,10gen-mms-agent-0.1,cron-1.4,jenkins-client-1.4,metrics-0.1,phpmoadmin-1.0,phpmyadmin-3.4,rockmongo-1.1,haproxy-1.4,diy-0.1,jbossas-7,jbosseap-6.0,jenkins-1.4,nodejs-0.6,perl-5.10,php-5.3,python-2.6,ruby-1.8,ruby-1.9,zend-5.6} 2>/dev/null) | $1
+}
+
+# Get the start order from installed carts
+function get_start_order {
+    echo $(get_component_order "cat")
+}
+
+# Get the stop order from installed carts
+function get_stop_order {
+    echo $(get_component_order "tac")
+}
+
 # Public: Start all processes in a given gear
 #
 # Examples:
@@ -18,68 +41,20 @@ function source_if_exists {
 #
 # Returns 0 on success
 function start_app {
-    for env_var in  $APP_HOME/.env/*_CTL_SCRIPT
-    do
-        . $env_var
-    done
-
     set_app_state started
 
-    for cmd in `awk 'BEGIN {
-                            for (a in ENVIRON)
-                            if (a ~ /DB_CTL_SCRIPT$/)
-                            print ENVIRON[a] }'`
+    for cart in $(get_start_order)
     do
-        run_as_user "$cmd start" || error "Failed to start ${cmd}" 121
-    done
-    for cmd in `awk 'BEGIN {
-                            for (a in ENVIRON)
-                                if ((a ~ /_CTL_SCRIPT$/) &&
-                                    !(a ~ /DB_CTL_SCRIPT$/) &&
-                                    !(a ~ /CART_CTL_SCRIPT$/))
-                                        print ENVIRON[a] }'`
-    do
-        run_as_user "$cmd start" || error "Failed to start ${cmd}" 121
-    done
-    for cmd in `awk 'BEGIN {
-                        for (a in ENVIRON)
-                            if (a ~ /CART_CTL_SCRIPT$/)
-                                print ENVIRON[a] }'`
-    do
-        run_as_user "$cmd start" || error "Failed to start ${cmd}" 121
+        run_as_user "${CARTRIDGE_BASE_PATH}/$cart/info/bin/app_ctl.sh start" || error "Failed to start ${cart}" 121
     done
 }
 
 function stop_app {
-    for env_var in  $APP_HOME/.env/*_CTL_SCRIPT
-    do
-        . $env_var
-    done
-
     set_app_state stopped
 
-    for cmd in `awk 'BEGIN {
-                        for (a in ENVIRON)
-                            if (a ~ /CART_CTL_SCRIPT$/)
-                                print ENVIRON[a] }'`
+    for cart in $(get_stop_order)
     do
-        run_as_user "$cmd stop" || echo "Failed to stop ${cmd}" 1>&2
-    done
-    for cmd in `awk 'BEGIN {
-                        for (a in ENVIRON)
-                        if ((a ~ /_CTL_SCRIPT$/) &&
-                            !(a ~ /DB_CTL_SCRIPT$/) &&
-                            !(a ~ /CART_CTL_SCRIPT$/))
-                                print ENVIRON[a] }'`
-    do
-        run_as_user "$cmd stop" || echo "Failed to stop ${cmd}" 1>&2
-    done
-    for cmd in `awk 'BEGIN {
-                            for (a in ENVIRON)
-                                if (a ~ /DB_CTL_SCRIPT$/)
-                                    print ENVIRON[a] }'`
-    do
-        run_as_user "$cmd stop" || echo "Failed to stop ${cmd}" 1>&2
+        run_as_user "${CARTRIDGE_BASE_PATH}/$cart/info/bin/app_ctl.sh stop" || error "Failed to stop ${cart}" 121
     done
 }
 
@@ -99,7 +74,6 @@ function source_if_exists {
 }
 
 function get_cartridge_instance_dir {
-    cartridge_type=$(get_cartridge_name_from_path)
     carttype=${1:-$cartridge_type}
     if [ -n "$carttype" ]; then
         echo "$APP_HOME/$carttype"
@@ -204,13 +178,10 @@ function only_cart_on_gear() {
 # Create cartridge specific variables
 #
 function create_standard_cart_env_vars {
-    cartridge_type=$(get_cartridge_name_from_path)
     CART_NS=$(convert_cart_name_to_namespace_id $cartridge_type)
     cinstancedir=$(get_cartridge_instance_dir)
     echo "export OPENSHIFT_${CART_NS}_LOG_DIR='$cinstancedir/logs/'" > \
                                       $APP_HOME/.env/OPENSHIFT_${CART_NS}_LOG_DIR
-    echo "export OPENSHIFT_${CART_NS}_CART_CTL_SCRIPT='$cinstancedir/${application}_ctl.sh'" > \
-                                      $APP_HOME/.env/OPENSHIFT_${CART_NS}_CART_CTL_SCRIPT
     echo "export OPENSHIFT_GEAR_TYPE='$cartridge_type'" > \
                                       $APP_HOME/.env/OPENSHIFT_GEAR_TYPE
 }
@@ -246,8 +217,8 @@ function create_cart_network_env_vars {
     CART_PORT=${2:-8080}
     CART_NS=$(convert_cart_name_to_namespace_id $cartridge_type)
 
-    echo "export OPENSHIFT_${CART_NS}_INTERNAL_IP='$CART_IP'" > $APP_HOME/.env/OPENSHIFT_${CART_NS}_IP
-    echo "export OPENSHIFT_${CART_NS}_INTERNAL_PORT='$CART_PORT'" > $APP_HOME/.env/OPENSHIFT_${CART_NS}_PORT
+    echo "export OPENSHIFT_${CART_NS}_IP='$CART_IP'" > $APP_HOME/.env/OPENSHIFT_${CART_NS}_IP
+    echo "export OPENSHIFT_${CART_NS}_PORT='$CART_PORT'" > $APP_HOME/.env/OPENSHIFT_${CART_NS}_PORT
 }
 
 function create_standard_repo_dir_env_var {
@@ -292,7 +263,6 @@ function create_standard_app_dirs {
 }
 
 function create_cartridge_instance_dir {
-    cartridge_type=$(get_cartridge_name_from_path)
     carttype=${1:-$cartridge_type}
     if [ -n "$carttype" ]; then
         mkdir -p "$APP_HOME/$carttype"
@@ -309,15 +279,16 @@ function create_app_dir_symlink {
 
 # Create simple application start / stop script
 function create_app_ctl_script {
-    rm -f "$APP_DIR/${application}_ctl.sh"
-    cat <<EOF >> "$APP_DIR/${application}_ctl.sh"
+    rm -f "$APP_DIR/${cartridge_type}_ctl.sh"
+    
+    cat <<EOF >> "$APP_DIR/${cartridge_type}_ctl.sh"
 #!/bin/bash -e
 
 set -x
 
 EOF
     if [ "$1" ]; then
-        cat <<EOF >> "$APP_DIR/${application}_ctl.sh"
+        cat <<EOF >> "$APP_DIR/${cartridge_type}_ctl.sh"
 # Expose which cartridge created the ctl script
 export CARTRIDGE_TYPE="$1"
 
@@ -325,7 +296,7 @@ EOF
     fi
 
 
-    cat <<EOF >> "$APP_DIR/${application}_ctl.sh"
+    cat <<EOF >> "$APP_DIR/${cartridge_type}_ctl.sh"
 # Import Environment Variables
 for f in ~/.env/*
 do
@@ -335,7 +306,7 @@ done
 app_ctl.sh \$1
 EOF
 
-    chmod +x "$APP_DIR/${application}_ctl.sh" || \
+    chmod +x "$APP_DIR/${cartridge_type}_ctl.sh" || \
         error "Failed to chmod new application scripts" 122
 
 }
@@ -369,7 +340,6 @@ function secure_conf_dirs {
 }
 
 function check_cartridge_dir_doesnt_exist {
-    cartridge_type=$(get_cartridge_name_from_path)
     if [ -d "$APP_HOME/$cartridge_type" ]; then
         error "${application}. Cartridge directory $APP_HOME/$cartridge_type already exists." 132
     fi
@@ -387,7 +357,6 @@ function rm_app_dir {
 }
 
 function rm_cartridge_instance_dir {
-    cartridge_type=$(get_cartridge_name_from_path)
     ctype=${1:-$cartridge_type}
     [ -n "$ctype" ]  &&  runcon -l s0-s0:c0.c1023 rm -rf "$APP_HOME/$ctype"
 }
@@ -482,7 +451,6 @@ function cart_props {
 }
 
 function setup_configure {
-    cartridge_type=$(get_cartridge_name_from_path)
     source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/git
     source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network
     source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
@@ -509,7 +477,6 @@ function setup_configure {
 }
 
 function setup_deconfigure {
-    cartridge_type=$(get_cartridge_name_from_path)
     source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/git
     source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network
     source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
@@ -525,7 +492,6 @@ function setup_deconfigure {
 }
 
 function setup_embedded_configure {
-    cartridge_type=$(get_cartridge_name_from_path)
     source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network
     source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
 
@@ -546,7 +512,6 @@ function setup_embedded_configure {
 }
 
 function setup_embedded_deconfigure {
-    cartridge_type=$(get_cartridge_name_from_path)
     source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/network
     source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/apache
 
@@ -573,8 +538,6 @@ function setup_basic_vars {
 }
 
 function setup_app_dir_vars {
-    cartridge_type=$(get_cartridge_name_from_path)
-
     APP_HOME="$GEAR_BASE_DIR/$uuid/"
     APP_DIR=`echo $APP_HOME/$cartridge_type | tr -s /`
     APP_REPO_DIR="$APP_HOME/app-root/repo"
